version: 2
updates:
    - package-ecosystem: "nuget"
      directory: "/NewAPI"
      schedule:
        interval: "daily"

    - package-ecosystem: "nuget"
      directory: "/NewAPITests"
      schedule:
        interval: "daily"
